import Post from "@/features/feed/Post";
import NewComment from "@/features/new-comment/NewComment";
import { trpc } from "@/utils/trpc";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import moment from "moment";
import Image from "next/image";

const Status: NextPage = () => {
  const router = useRouter();
  const id = router.query.id as string;
  const { data, isLoading, isError } = trpc.post.getPost.useQuery({ id });

  if (isLoading) return <div>Loading...</div>;
  if (isError) return <div>Error...</div>;
  if (!data) return <div>No data</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Post post={data} />
      <NewComment postId={id} />
      <div>comments</div>
      {data.comments.map((comment) => {
        return (
          <>
            <div className="w-full rounded-xl bg-white p-4">
              <div className="flex gap-2">
                <Image
                  className="rounded-full"
                  width={50}
                  height={50}
                  alt={"https://randomuser.me/api/portraits/lego/1.jpg"}
                  src={"https://randomuser.me/api/portraits/lego/1.jpg"}
                />
                <div>
                  <div className="flex gap-2">
                    <span className="font-bold">{comment.user.username}</span>
                    {/* <span className="">@{post.user.username}</span> */}
                    <span className="font-light">
                      {moment(comment.updatedAt).fromNow()}
                    </span>
                  </div>

                  {comment.content}
                </div>
              </div>
            </div>
          </>
        );
      })}
    </>
  );
};

export default Status;
