import Feed from "@/features/feed/Feed";
import NewPost from "@/features/new-post/NewPost";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session && <NewPost />}
      <Feed />
    </>
  );
};

export default Home;
